[WIP] Assistant sdk
yandex-cloud/nodejs-sdk pull request #178
Opened 2024-12-15 00:54 UTC by GermanVor

2024-12-18 06:58 UTC, DavyJohnes requested changes

2024-12-18 06:58 UTC, DavyJohnes commented on .eslintrc.json
> -    "@typescript-eslint/indent": ["error", 4],
Это правило prettier'ом хэндлится?

2024-12-18 06:58 UTC, DavyJohnes commented on clients/ai-assistants-v1/index.ts
> +export * as SDK from './sdk';
Че т я не очень понял, а откуда оно взялось? Я в proto не вижу каких-либо модулей `sdk`.

2024-12-18 06:58 UTC, DavyJohnes commented on package.json
> +    "ai-foundation_models-v1/sdk",
Кажется избыточным, предыдущий пункт должен включать и текущий тоже.

2024-12-18 10:10 UTC, GermanVor commented on clients/ai-assistants-v1/index.ts
> +export * as SDK from './sdk';
ты про то, что оно появилось в // generated file ?

2024-12-18 10:12 UTC, GermanVor commented on package.json
> +    "ai-foundation_models-v1/sdk",
Я вот не уверен, у меня локально даже так ts ругается на sdk - что оно не видит. 
Мб у меня локальный линтер с ума сходит из за подмен либ. 

Поэтому добавил бек док в виде

export * as SDK from './sdk';

2024-12-18 10:17 UTC, GermanVor commented on .eslintrc.json
> -    "@typescript-eslint/indent": ["error", 4],
https://github.com/yandex-cloud/nodejs-sdk/pull/178/commits/6b0b99791f3dbe3bc5c9f7b5e825a9a8ad1368c5

не знаю что это за правило, случайно удалил

2024-12-24 11:50 UTC, GermanVor commented on package.json
> +    "ai-foundation_models-v1/sdk",
`Мб у меня локальный линтер с ума сходит из за подмен либ` - наверное да, вроде проросло

[28ca8af](https://github.com/yandex-cloud/nodejs-sdk/pull/178/commits/28ca8af2ddb95262e3ded8549d71b001d8737754)

2024-12-24 11:50 UTC, GermanVor commented on clients/ai-assistants-v1/index.ts
> +export * as SDK from './sdk';
[28ca8af](https://github.com/yandex-cloud/nodejs-sdk/pull/178/commits/28ca8af2ddb95262e3ded8549d71b001d8737754)

2025-01-10 13:18 UTC, merged